name: nytimes
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.3
  url_launcher: ^6.0.9
  cached_network_image: ^3.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  webview_flutter: ^2.0.10
  animations: ^2.0.1

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
   - family: UnifrakturCook
     fonts:
       - asset: fonts\UnifrakturCook-Bold.ttf
   - family: RacingSansOne
     fonts:
       - asset: fonts\RacingSansOne-Regular.ttf
   - family: BerkshireSwash
     fonts:
       - asset: fonts\BerkshireSwash-Regular.ttf

